### PR TITLE
Watch directories recursively.

### PR DESCRIPTION
**Pull request by tsg**
This is useful for projects that have multiple sub-packages. The
change adds a watcher to all subdirectories recursively. You would
typically execute it like this:

   goautotest ./...

### CODE REVIEW

**Comment by darxriggs** [comment]
@ryanslade Is there a chance that you find some time to merge this PR?

**Comment by ryanslade** [comment]
Hi Rene

I'm currently travelling without access to a computer. I'll have a look
when I'm back in a couple of weeks.

Thanks for the PR.

Ryan

**Comment by tsg** [comment]
Cleaning up my old PRs.

**Comment by ryanslade** [comment]
I guess I didn't get back to it as promised 😄

**Comment by tsg** [comment]
No worries :)

**Pull request closed without merging**
